spring.application.name=pack-it-backend
server.port=${PORT:8080}

spring.datasource.url=jdbc:h2:file:${PACKIT_DB_PATH:./packit-db};DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=${PACKIT_DB_USERNAME:sa}
spring.datasource.password=${PACKIT_DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_vidDVo9o0

app.cors.allowed-origins=${PACKIT_CORS_ALLOWED_ORIGINS:http://localhost:4200}
